# Generated by Django 5.2.11 on 2026-08-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0006_auditableentity_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('category', models.CharField(choices=[('CASH_SHORTAGE', 'Cash Shortage'), ('FORGERY', 'Forgery'), ('THEFT', 'Theft'), ('SYSTEM_GLITCH', 'System Glitch / IT Failure'), ('PROCESS_VIOLATION', 'Process Violation'), ('OTHER', 'Other')], max_length=50)),
                ('discovery_time', models.DateTimeField()),
                ('responsible_organ', models.CharField(max_length=255)),
                ('involved_system', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_involved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recommended_action', models.TextField()),
                ('escalation_procedure', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INVESTIGATING', 'Under Investigation'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(limit_choices_to={'entity_type': 'BRANCH'}, on_delete=django.db.models.deletion.CASCADE, related_name='irregularities', to='audits.auditableentity')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_irregularities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
