# Generated by Django 5.2.11 on 2026-08-18 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auditableentity_is_deleted'),
        ('irregularities', '0002_incidentcategory_incidentsystem_responsibleorgan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentAuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('audit_area', models.CharField(max_length=100)),
                ('date_identified', models.DateField()),
                ('description', models.TextField()),
                ('applicable_procedure', models.TextField(blank=True, null=True)),
                ('risk_impact', models.CharField(choices=[('FINANCIAL', 'Financial'), ('OPERATIONAL', 'Operational'), ('COMPLIANCE', 'Compliance'), ('CUSTOMER', 'Customer'), ('FRAUD', 'Fraud'), ('TECHNOLOGY', 'Technology'), ('REPUTATIONAL', 'Reputational')], max_length=50)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('required_corrective_action', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Reported'), ('RESPONSE_REQUIRED', 'Management Response Required'), ('ACTION_PLAN_SUBMITTED', 'Action Plan Submitted'), ('UNDER_RECTIFICATION', 'Under Rectification'), ('EVIDENCE_SUBMITTED', 'Evidence Submitted'), ('PENDING_VERIFICATION', 'Pending Auditor Verification'), ('CLOSED', 'Verified and Closed'), ('RETURNED', 'Rejected/Returned for Further Action'), ('OVERDUE', 'Overdue'), ('ESCALATED', 'Escalated')], default='DRAFT', max_length=30)),
                ('management_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_findings', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(limit_choices_to={'entity_type': 'BRANCH'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_findings', to='audits.auditableentity')),
                ('responsible_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audit_evidence/%Y/%m/')),
                ('is_management_evidence', models.BooleanField(default=False, help_text='True if uploaded by management as proof of rectification')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='irregularities.residentauditfinding')),
            ],
        ),
        migrations.CreateModel(
            name='FindingAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='irregularities.residentauditfinding')),
            ],
        ),
    ]
