# Generated by Django 5.2.11 on 2026-08-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irregularities', '0003_residentauditfinding_findingevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('unit_type', models.CharField(choices=[('BRANCH', 'Branch'), ('DISTRICT_OFFICE', 'District Office'), ('REGIONAL_OFFICE', 'Regional Office'), ('HEAD_OFFICE', 'Head Office'), ('DEPARTMENT', 'Department'), ('OTHER', 'Other')], default='BRANCH', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='irregularities.organizationalunit')),
            ],
            options={
                'ordering': ['unit_type', 'name'],
            },
        ),
    ]
