# Generated by Django 6.1 on 2026-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditdepartment_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHIEF', 'Chief Internal Audit'), ('DIRECTOR', 'Director / Department Head'), ('TEAM_MANAGER', 'Team Manager'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
