# Generated by Django 6.1 on 2026-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_auditdepartment_level_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='auditdepartment',
            name='level',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('CHIEF', 'Chief Internal Audit'), ('DIRECTORATE', 'Directorate'), ('TEAM', 'Team')], max_length=20),
        ),
    ]
