# Generated by Django 6.1 on 2026-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_employee_id_user_job_title_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('CHIEF', 'Chief Internal Audit'), ('DIRECTOR', 'Director / Department Head'), ('TEAM_MANAGER', 'Team Manager'), ('TEAM_MEMBER', 'Team Member'), ('AUDITOR', 'Auditor'), ('AUDITEE', 'Auditee'), ('VISITOR', 'Visitor')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
