# Generated by Django 6.1 on 2026-08-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('ACTIVATED', 'Activated'), ('SUSPENDED', 'Suspended'), ('ROLE_CHANGED', 'Role Changed'), ('DEPT_CHANGED', 'Department Changed'), ('PROFILE_CHANGED', 'Profile Changed'), ('PASSWORD_CHANGED', 'Password Changed'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('CREATED', 'Created')], max_length=20),
        ),
    ]
