# Generated by Django 5.1 on 2026-08-11 10:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userauditlog_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditDepartment',
            new_name='Department',
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('DIVISION', 'Division / Executive'), ('DIRECTORATE', 'Directorate / Department'), ('TEAM', 'Team')], max_length=20),
        ),
    ]
