# Generated by Django 5.2.11 on 2026-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20260811_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_public_content',
            field=models.BooleanField(default=False),
        ),
    ]
