# Generated by Django 5.2.11 on 2026-08-17 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_auditperiod_options_and_more'),
        ('users', '0015_alter_departmentperformanceplan_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('entity_type', models.CharField(choices=[('BRANCH', 'Branch'), ('DEPARTMENT', 'Head Office Department'), ('IT_SYSTEM', 'IT System'), ('PROCESS', 'Business Process'), ('OTHER', 'Other')], max_length=20)),
                ('risk_rating', models.CharField(choices=[('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('LOW', 'Low Risk')], default='MEDIUM', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_audited_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Auditable Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnnualAuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('total_budgeted_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_annual_plans', to=settings.AUTH_USER_MODEL)),
                ('audit_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plan', to='audits.auditperiod')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annual_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('FIELDWORK', 'Fieldwork'), ('REPORTING', 'Reporting'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditors', models.ManyToManyField(blank=True, related_name='assigned_engagements', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_engagements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('condition', models.TextField(help_text='What is the current state?')),
                ('criteria', models.TextField(help_text='What should be the state?')),
                ('cause', models.TextField(help_text='Why did the condition occur?')),
                ('effect', models.TextField(help_text='What is the impact/risk?')),
                ('recommendation', models.TextField(help_text='What should be done to fix it?')),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('management_response', models.TextField(blank=True, null=True)),
                ('action_plan_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING_FOLLOWUP', 'Pending Follow-up')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('overall_rating', models.CharField(blank=True, help_text='e.g. Satisfactory, Needs Improvement', max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('ISSUED', 'Issued')], default='DRAFT', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='audit_final_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='audits.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_targeted', models.CharField(choices=[('Q1', 'Quarter 1 (Jul-Sep)'), ('Q2', 'Quarter 2 (Oct-Dec)'), ('Q3', 'Quarter 3 (Jan-Mar)'), ('Q4', 'Quarter 4 (Apr-Jun)')], max_length=2)),
                ('budgeted_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_audits', to='audits.annualauditplan')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_planned_audits', to='users.department')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_audits', to='audits.auditableentity')),
            ],
            options={
                'unique_together': {('annual_plan', 'entity', 'quarter_targeted')},
            },
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='planned_audit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='audits.plannedaudit'),
        ),
        migrations.CreateModel(
            name='RiskControlMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('identified_risk', models.TextField()),
                ('control_description', models.TextField()),
                ('control_design_assessment', models.CharField(blank=True, max_length=100, null=True)),
                ('control_operating_effectiveness', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcm_entries', to='audits.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='DRAFT', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='workpapers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_papers', to='audits.auditengagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_workpapers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workpapers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
