# Generated by Django 5.2.11 on 2026-08-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auditableentity_annualauditplan_auditengagement_and_more'),
        ('users', '0015_alter_departmentperformanceplan_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='audit_checklists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditableentity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditable_entities', to='users.department'),
        ),
        migrations.AddField(
            model_name='auditableentity',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditableentity',
            name='attached_checklists_templates',
            field=models.ManyToManyField(blank=True, related_name='entities', to='audits.checklisttemplate'),
        ),
    ]
