# Generated by Django 5.2.11 on 2026-08-17 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_checklisttemplate_auditableentity_department_and_more'),
        ('users', '0016_user_expertise_user_qualifications_user_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditengagement',
            name='engagement_letter',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='wbs',
            field=models.JSONField(blank=True, default=list, help_text='Work Breakdown Structure tasks', null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='auditee_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='is_sent_to_auditees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='loss_figures',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='rectification_validation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='sla_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_type', models.CharField(max_length=100)),
                ('directive_number', models.CharField(max_length=100)),
                ('control_name', models.CharField(max_length=255)),
                ('assessment_criteria', models.TextField()),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('PARTIAL', 'Partial'), ('NON_COMPLIANT', 'Non-Compliant')], default='COMPLIANT', max_length=50)),
                ('last_assessed_date', models.DateField(auto_now=True)),
                ('mapped_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_controls', to='audits.auditableentity')),
            ],
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_escalations', to=settings.AUTH_USER_MODEL)),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_escalations', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_escalations', to=settings.AUTH_USER_MODEL)),
                ('source_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_escalations', to='users.department')),
                ('target_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_escalations', to='users.department')),
            ],
        ),
    ]
