# Generated by Django 5.2.11 on 2026-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_auditengagement_engagement_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditableentity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
