# Generated by Django 6.1 on 2026-08-10 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('DOWNLOAD_DENIED', 'Download Denied'), ('CREATED', 'Created'), ('UPLOADED', 'Uploaded'), ('METADATA_UPDATED', 'Metadata Updated'), ('VERSION_CREATED', 'Version Created'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('AUTHORIZATION_GRANTED', 'Authorization Granted'), ('AUTHORIZATION_REVOKED', 'Authorization Revoked'), ('AUTHORIZATION_EXPIRED', 'Authorization Expired'), ('DELETION_REQUESTED', 'Deletion Requested'), ('DELETION_APPROVED', 'Deletion Approved'), ('DELETION_REJECTED', 'Deletion Rejected'), ('PERMANENT_DELETION', 'Permanent Deletion'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('previous_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Audit Log',
                'verbose_name_plural': 'Document Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
