# Generated by Django 5.2.11 on 2026-08-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_make_audit_period_quarter_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', '-category'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
