# Generated by Django 4.2.23 on 2025-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='Format: YYYY-YY (e.g., 2025-26)', max_length=7, unique=True, verbose_name='fiscal year')),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1 (Jul-Sep)'), ('Q2', 'Quarter 2 (Oct-Dec)'), ('Q3', 'Quarter 3 (Jan-Mar)'), ('Q4', 'Quarter 4 (Apr-Jun)')], max_length=2, verbose_name='quarter')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'audit period',
                'verbose_name_plural': 'audit periods',
                'ordering': ['-fiscal_year', 'quarter'],
                'unique_together': {('fiscal_year', 'quarter')},
            },
        ),
    ]
