# Generated by Django 4.2.23 on 2025-11-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditperiod',
            options={'ordering': ['-fiscal_year'], 'verbose_name': 'audit period', 'verbose_name_plural': 'audit periods'},
        ),
        migrations.AlterUniqueTogether(
            name='auditperiod',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='auditperiod',
            name='quarter',
        ),
    ]
