# Generated by Django 5.2.11 on 2026-08-17 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Background artistic image for certificates', null=True, upload_to='certificates/')),
                ('signature_image', models.ImageField(blank=True, help_text='Signature image for Chief Internal Auditor', null=True, upload_to='certificates/')),
                ('chief_auditor_name', models.CharField(default='Chief Internal Auditor', max_length=255)),
                ('organization_name', models.CharField(default='Coop Bank Internal Audit Excellence Center', max_length=255)),
                ('motto', models.CharField(blank=True, help_text='e.g. Excellence in Auditing', max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Empowering Trust', max_length=255, null=True)),
            ],
            options={
                'db_table': 'public_pages_certificatesettings',
            },
        ),
        migrations.CreateModel(
            name='LearningPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_url', models.URLField(help_text='The main iframe src URL for the playlist or video', max_length=500)),
                ('playlist_id', models.CharField(blank=True, help_text='YouTube Playlist ID for fetching episodes', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which playlists appear on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_pages_learningplaylist',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Video Only'), ('text', 'Text Only'), ('mixed', 'Video and Text'), ('quiz', 'Quiz')], default='video', max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='YouTube URL if applicable', max_length=500)),
                ('content_text', models.TextField(blank=True, help_text='Text content or instructions')),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='lms.learningplaylist')),
            ],
            options={
                'db_table': 'public_pages_learningepisode',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.IntegerField(default=70, help_text='Percentage required to pass')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lms.learningepisode')),
            ],
            options={
                'db_table': 'public_pages_quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.quiz')),
            ],
            options={
                'db_table': 'public_pages_quizquestion',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.quizquestion')),
            ],
            options={
                'db_table': 'public_pages_quizanswer',
            },
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_pages_userquizattempt',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.learningplaylist')),
            ],
            options={
                'db_table': 'public_pages_courseenrollment',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lms.learningepisode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_pages_lessonprogress',
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
