# Generated by Django 5.2.11 on 2026-08-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='last_position',
            field=models.IntegerField(default=0, help_text='Last watched position in seconds'),
        ),
    ]
