# Generated by Django 5.2.11 on 2026-08-17 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_can_manage_public_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPerformancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('long_term_plan', models.TextField(blank=True, help_text='Long-term strategic vision and plan.', null=True)),
                ('short_term_plan', models.TextField(blank=True, help_text='Short-term objectives and execution plan.', null=True)),
                ('performance_execution', models.TextField(blank=True, help_text='Detailed achievements and execution metrics.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_plans', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_plans', to='users.department')),
            ],
            options={
                'ordering': ['-year', 'department__name'],
                'unique_together': {('department', 'year')},
            },
        ),
    ]
