# Generated by Django 5.2.11 on 2026-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_departmentperformanceplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentperformanceplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='annual_target_audits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='engagement_activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='plan_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Plan'), ('ENGAGEMENT', 'Specific Engagement Plan')], default='ANNUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='q1_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='q2_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='q3_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='q4_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='departmentperformanceplan',
            name='title',
            field=models.CharField(blank=True, help_text='Required for Engagement Plans', max_length=255),
        ),
    ]
