# Generated by Django 5.2.11 on 2026-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_expertise_user_qualifications_user_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_analytics_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_audit_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_dms_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_irregularity_access',
            field=models.BooleanField(default=False),
        ),
    ]
