# Generated by Django 5.2.11 on 2026-08-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_has_analytics_access_user_has_audit_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_lms_course',
            field=models.BooleanField(default=False),
        ),
    ]
