# Generated by Django 5.2.11 on 2026-08-20 08:48

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_can_create_lms_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsystemAccessAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Subsystem Access Analytic',
                'verbose_name_plural': 'Subsystem Access Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
