# Generated by Django 4.2.23 on 2025-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_auditperiod_options_and_more'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-audit_period__fiscal_year', '-quarter', '-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1 (Jul-Sep)'), ('Q2', 'Quarter 2 (Oct-Dec)'), ('Q3', 'Quarter 3 (Jan-Mar)'), ('Q4', 'Quarter 4 (Apr-Jun)')], default=12, help_text='Select the quarter for this document', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('audit_period', 'quarter', 'title')},
        ),
    ]
