# Generated by Django 4.2.23 on 2025-11-19 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_alter_document_unique_together_document_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-category', '-audit_period__fiscal_year', '-quarter', '-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='audit_type',
            field=models.CharField(blank=True, choices=[('BRANCH', 'Branch Audit'), ('IT', 'IT Audit'), ('INVESTIGATION', 'Investigation Audit'), ('HEAD_OFFICE', 'Head Office Organ Audit'), ('IFB', 'IFB Audit')], help_text='Select audit type (for audit reports only)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('AUDIT_REPORTS', 'Audit Reports'), ('GUIDELINES', 'Guidelines'), ('CHARTERS', 'Charters'), ('FRAMEWORKS', 'Frameworks'), ('POLICIES', 'Policies'), ('PROCEDURES', 'Procedures'), ('MANUALS', 'Manuals'), ('TEMPLATES', 'Templates'), ('OTHER', 'Other Documents')], default='AUDIT_REPORTS', help_text='Select document category', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
