# Generated by Django 4.2.23 on 2025-11-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_alter_document_options_document_audit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental Backup'), ('DOCUMENTS_ONLY', 'Documents Only'), ('DATABASE_ONLY', 'Database Only')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=20)),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('backed_up_documents', models.IntegerField(default=0)),
                ('failed_documents', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('include_files', models.BooleanField(default=True)),
                ('include_database', models.BooleanField(default=True)),
                ('compression', models.BooleanField(default=True)),
                ('encryption_key', models.TextField(blank=True)),
                ('error_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Operation',
                'verbose_name_plural': 'Backup Operations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('backup_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.backupoperation')),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
