# Generated by Django 4.2.23 on 2026-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0006_backupoperation_backuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='accessible_documents', to='auth.group'),
        ),
    ]
