# Generated by Django 6.1 on 2026-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_allowed_groups'),
        ('users', '0002_auditdepartment_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='accessible_documents_by_dept', to='users.auditdepartment'),
        ),
    ]
