# Generated by Django 6.1 on 2026-08-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_allowed_departments'),
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The internal audit structure department that owns this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to='users.auditdepartment'),
        ),
    ]
