# Generated by Django 6.1 on 2026-08-10 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_deletion_reason_document_deletion_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryaccess',
            name='can_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='temporaryaccess',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentapprovallog',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Requested Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELETION_REQUESTED', 'Requested Deletion'), ('DELETION_APPROVED', 'Approved Deletion'), ('DELETION_REJECTED', 'Rejected Deletion'), ('AUTHORIZATION_GRANTED', 'Authorization Granted'), ('AUTHORIZATION_REVOKED', 'Authorization Revoked')], max_length=30),
        ),
    ]
