# Generated by Django 6.1 on 2026-08-10 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0011_temporaryaccess_can_print_temporaryaccess_can_view_and_more'),
        ('users', '0003_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='download_allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='downloadable_documents_by_dept', to='users.auditdepartment'),
        ),
        migrations.AddField(
            model_name='document',
            name='download_allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='downloadable_documents', to='auth.group'),
        ),
        migrations.AddField(
            model_name='document',
            name='download_allowed_users',
            field=models.ManyToManyField(blank=True, related_name='downloadable_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='download_restricted',
            field=models.BooleanField(default=False, help_text='If true, only explicitly allowed users can download this document.'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('DOWNLOAD_DENIED', 'Download Denied')], max_length=20),
        ),
    ]
