# Generated by Django 6.1 on 2026-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_download_allowed_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Correction')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentapprovallog',
            name='action',
            field=models.CharField(choices=[('REQUESTED', 'Requested Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('DELETION_REQUESTED', 'Requested Deletion'), ('DELETION_APPROVED', 'Approved Deletion'), ('DELETION_REJECTED', 'Rejected Deletion'), ('AUTHORIZATION_GRANTED', 'Authorization Granted'), ('AUTHORIZATION_REVOKED', 'Authorization Revoked')], max_length=30),
        ),
    ]
