# Generated by Django 6.1 on 2026-08-10 13:56

from django.db import migrations


def migrate_audit_logs(apps, schema_editor):
    DocumentAccessLog = apps.get_model('documents', 'DocumentAccessLog')
    DocumentApprovalLog = apps.get_model('documents', 'DocumentApprovalLog')
    DocumentAuditLog = apps.get_model('documents', 'DocumentAuditLog')

    # Migrate Access Logs
    for log in DocumentAccessLog.objects.all():
        doc_title = log.document.title if log.document else ''
        username = log.user.username if log.user else ''
        role = log.user.role if log.user else ''
        dept_name = log.user.department.name if log.user and log.user.department else ''
        
        # Determine team/department breakdown
        team_name = ''
        if log.user and log.user.department:
            if log.user.department.level == 'TEAM':
                team_name = dept_name
                dept_name = log.user.department.parent.name if log.user.department.parent else ''

        DocumentAuditLog.objects.create(
            document=log.document,
            document_title=doc_title,
            user=log.user,
            user_username=username,
            role=role,
            department=dept_name,
            team=team_name,
            action=log.action,
            ip_address=log.ip_address,
            result='SUCCESS',  # Assuming SUCCESS for old VIEW/DOWNLOAD except if DOWNLOAD_DENIED
            comments='',
        )
        
        # update timestamp (auto_now_add makes it now by default unless we set it directly)
        # We need to update it after creation
        audit_log = DocumentAuditLog.objects.last()
        audit_log.timestamp = log.timestamp
        if log.action == 'DOWNLOAD_DENIED':
            audit_log.result = 'DENIED'
        audit_log.save()

    # Migrate Approval Logs
    for log in DocumentApprovalLog.objects.all():
        doc_title = log.document.title if log.document else ''
        username = log.user.username if log.user else ''
        role = log.user.role if log.user else ''
        dept_name = log.user.department.name if log.user and log.user.department else ''
        
        team_name = ''
        if log.user and log.user.department:
            if log.user.department.level == 'TEAM':
                team_name = dept_name
                dept_name = log.user.department.parent.name if log.user.department.parent else ''

        DocumentAuditLog.objects.create(
            document=log.document,
            document_title=doc_title,
            user=log.user,
            user_username=username,
            role=role,
            department=dept_name,
            team=team_name,
            action=log.action,
            comments=log.comments,
            result='SUCCESS'
        )
        audit_log = DocumentAuditLog.objects.last()
        audit_log.timestamp = log.timestamp
        audit_log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_is_archived_documentauditlog'),
    ]

    operations = [
        migrations.RunPython(migrate_audit_logs, reverse_code=migrations.RunPython.noop),
    ]
