# Generated by Django 6.1 on 2026-08-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_migrate_audit_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentapprovallog',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentapprovallog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DocumentAccessLog',
        ),
        migrations.DeleteModel(
            name='DocumentApprovalLog',
        ),
    ]
