# Generated by Django 6.1 on 2026-08-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_documentapprovallog_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccess',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
    ]
