# Generated by Django 6.1 on 2026-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_temporaryaccess_authorizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Optional document description', null=True),
        ),
    ]
