# Generated by Django 5.2.11 on 2026-08-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_auditperiod_options_and_more'),
        ('documents', '0020_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='audit_period',
            field=models.ForeignKey(blank=True, help_text='Required for Audit Reports only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='audits.auditperiod'),
        ),
        migrations.AlterField(
            model_name='document',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1 (Jul-Sep)'), ('Q2', 'Quarter 2 (Oct-Dec)'), ('Q3', 'Quarter 3 (Jan-Mar)'), ('Q4', 'Quarter 4 (Apr-Jun)')], help_text='Required for Audit Reports only', max_length=2, null=True),
        ),
    ]
