# Generated by Django 5.2.11 on 2026-08-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0005_certificatesettings_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesettings',
            name='motto',
            field=models.CharField(blank=True, help_text='e.g. Excellence in Auditing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g. Empowering Trust', max_length=255, null=True),
        ),
    ]
