# Generated by Django 5.2.11 on 2026-08-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_url', models.URLField(help_text='The main iframe src URL for the playlist or video', max_length=500)),
                ('playlist_id', models.CharField(blank=True, help_text='YouTube Playlist ID for fetching episodes', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which playlists appear on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(help_text='Full YouTube URL for the episode', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='public_pages.learningplaylist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
