# Generated by Django 5.2.11 on 2026-08-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0003_learningepisode_content_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Background artistic image for certificates', null=True, upload_to='certificates/')),
                ('signature_image', models.ImageField(blank=True, help_text='Signature image for Chief Internal Auditor', null=True, upload_to='certificates/')),
                ('chief_auditor_name', models.CharField(default='Chief Internal Auditor', max_length=255)),
            ],
        ),
    ]
