# Generated by Django 5.2.11 on 2026-08-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0004_certificatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesettings',
            name='organization_name',
            field=models.CharField(default='Coop Bank Internal Audit Excellence Center', max_length=255),
        ),
    ]
