# Generated by Django 5.2.11 on 2026-08-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0007_learningplaylist_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateSettings',
        ),
        migrations.RemoveField(
            model_name='learningepisode',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='learningplaylist',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='LearningEpisode',
        ),
        migrations.DeleteModel(
            name='LearningPlaylist',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
    ]
