# Generated by Django 5.2.11 on 2026-08-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('connection_string', models.CharField(help_text='e.g. postgresql://user:pass@localhost:5432/dbname', max_length=512)),
                ('driver', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('SQLSERVER', 'SQL Server'), ('ORACLE', 'Oracle')], default='POSTGRES', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('script_type', models.CharField(choices=[('SQL', 'SQL Query')], default='SQL', max_length=50)),
                ('code_content', models.TextField(help_text='The actual SQL query to execute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='analytics.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=50)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.auditscript')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_data', models.JSONField(help_text='The row data that triggered the exception')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Under Review'), ('DISMISSED', 'Dismissed / False Positive'), ('ESCALATED', 'Escalated to Audit Finding')], default='NEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='analytics.scriptexecution')),
            ],
        ),
    ]
